name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Install Dependencies
        run: npm ci
        timeout-minutes: 5

      - name: Build Windows Executable
        run: npm run dist:win
        env:
          # Forces electron-builder and @electron/rebuild to print continuous, verbose internal logs
          DEBUG: electron-builder,electron-rebuild:*
        timeout-minutes: 15

      - uses: actions/upload-artifact@v4
        with:
          name: compile-windows
          path: dist/*.exe